[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.0'  # Set the Solidity version to 0.8.0


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
